CREATE DATABASE `gulimall_oms` CHARACTER SET 'utf8mb4';
CREATE DATABASE `gulimall_pms` CHARACTER SET 'utf8mb4';
CREATE DATABASE `gulimall_sms` CHARACTER SET 'utf8mb4';
CREATE DATABASE `gulimall_ums` CHARACTER SET 'utf8mb4';
CREATE DATABASE `gulimall_wms` CHARACTER SET 'utf8mb4';